# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  # Name the workflow "welcome"
  test:
    parameters:
      package:
        type: string
    docker:
      - image: silex/emacs:27-ci-cask
    steps:
      - checkout

      # install nodejs which is needed to setup tide-mode
      # but only for the javascript test
      - when:
          condition:
            equal: ["javascript", <<parameters.package>>]
          steps:
            - node/install:
                install-npm: false
            - run: apt-get update
            - run: apt-get install unzip
            - run: curl -fsSL https://deno.land/install.sh | sh
            - run: ln -s /root/.deno/bin/deno /bin/deno



      # restore cach
      - restore_cache:
          key: cask-<<parameters.package>>-{{ checksum "packages/<<parameters.package>>/Cask" }}-{{ checksum "packages/<<parameters.package>>/frontside-<<parameters.package>>.el" }}

      # install packages
      - run:
          command: cask install
          working_directory: ~/project/packages/<<parameters.package>>

      - save_cache:
          key: cask-<<parameters.package>>-{{ checksum "packages/<<parameters.package>>/Cask" }}-{{ checksum "packages/<<parameters.package>>/frontside-<<parameters.package>>.el" }}
          paths: [packages/<<parameters.package>>/.cask]
      # run tests
      - run:
          command: cask exec buttercup
          working_directory: ~/project/packages/<<parameters.package>>

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              package: ["javascript", "windowing"]
